### ISSUE TITLE
Eclipse setup

### ISSUE THREAD

**Issue by fantom-x** [yetisno/ACD-JAPI#3]
HI, I am trying to set up this as a project in Eclipse and am missing some dependencies: com.ning.http.client and com.google.gson. Can you point me to location of those source files? Tried searching google, but getting broken and misleading links...

**Comment by yetisno** [comment]
This is `gradle` project!

Eclipse also support `gradle`.

Build package by `gradle build` and it will download and linked. Or you can download it from here http://mvnrepository.com/artifact/com.ning/async-http-client/1.9.3 and http://mvnrepository.com/artifact/com.google.code.gson/gson/2.3.1

or just add this project to dependency by maven repository http://mvnrepository.com/artifact/org.yetiz.lib/ACD-JAPI/1.1.1

**Comment by fantom-x** [comment]
Thx, I tried importing it as an existing gradle project and got this error below. Any suggestions?

```
Loading Gradle project preview failed due to an error in the referenced Gradle build.
Could not fetch model of type 'GradleBuild' using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.2-bin.zip'.

Build file 'ACD-JAPI/build.gradle' line: 97
A problem occurred evaluating root project 'ACD-JAPI'.
No such property: ossrhUsername for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

```

**Comment by fantom-x** [comment]
This is the exception I am getting when building from command line. 

```
gradle -v

------------------------------------------------------------
Gradle 2.13
------------------------------------------------------------

Build time:   2016-04-25 04:10:10 UTC
Build number: none
Revision:     3b427b1481e46232107303c90be7b05079b05b1c

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_65 (Oracle Corporation 25.65-b01)
OS:           Linux 4.1.19-v7+ arm

```

```
Caused by: groovy.lang.MissingPropertyException: No such property: ossrhUsername for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer
    at build_defc6y9qevvssmkb9r29w160f$_run_closure11$_closure14$_closure16$_closure18.doCall(/root/ACD-JAPI/build.gradle:97)
    at build_defc6y9qevvssmkb9r29w160f$_run_closure11$_closure14$_closure16$_closure18.doCall(/root/ACD-JAPI/build.gradle)
    at org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer.methodMissing(DefaultGroovyMavenDeployer.groovy:38)
    at org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer.invokeMethod(DefaultGroovyMavenDeployer.groovy)
    at build_defc6y9qevvssmkb9r29w160f$_run_closure11$_closure14$_closure16.doCall(/root/ACD-JAPI/build.gradle:96)
    at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
    at org.gradle.api.internal.artifacts.DefaultArtifactRepositoryContainer.addRepository(DefaultArtifactRepositoryContainer.java:87)
    at org.gradle.api.publication.maven.internal.DefaultMavenRepositoryHandlerConvention.mavenDeployer(DefaultMavenRepositoryHandlerConvention.java:43)
    at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:236)
    at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:130)
    at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:212)
    at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:150)
    at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:150)
    at org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler_Decorated.invokeMethod(Unknown Source)
    at build_defc6y9qevvssmkb9r29w160f$_run_closure11$_closure14.doCall(/root/ACD-JAPI/build.gradle:93)
    at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
    at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
    at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:110)
    at org.gradle.api.internal.artifacts.DefaultArtifactRepositoryContainer.configure(DefaultArtifactRepositoryContainer.java:66)
    at org.gradle.api.internal.artifacts.DefaultArtifactRepositoryContainer.configure(DefaultArtifactRepositoryContainer.java:33)
    at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:59)
    at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
    at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:91)
    at org.gradle.api.tasks.Upload.repositories(Upload.java:118)
    at build_defc6y9qevvssmkb9r29w160f$_run_closure11.doCall(/root/ACD-JAPI/build.gradle:92)
    at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
    at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
    at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:110)
    at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:488)
    at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:58)
    at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:59)
    at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
    at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:91)
    at org.gradle.api.internal.DefaultNamedDomainObjectCollection$ContainerElementsDynamicObject.invokeMethod(DefaultNamedDomainObjectCollection.java:341)
    at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:150)
    at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
    at build_defc6y9qevvssmkb9r29w160f.run(/root/ACD-JAPI/build.gradle:91)
    at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
    ... 47 more

```

**Comment by yetisno** [comment]
This exception is a bug of build script, it's about upload jar to maven central repository.
I have fix it on https://github.com/yetisno/ACD-JAPI/commit/b91bad5a24ccdb0e0436d8d5822ed355c5b020c1 by comment upload script, please fetch and pull latest commit!
Thanks for your report!

**Comment by fantom-x** [comment]
Thx; it works now in Eclipse and from command line.
